# e_arima()

e_arima<-function(explaining=0){
if(explaining==0) {
cat(" library(aj412s2);library(aj412ts) ", '\n')
cat(" library(forecast);library(ggfortify) ", '\n')
cat(" library(strucchange);library(changepoint) ", '\n')
cat("     ", '\n')
cat("\033[1;32m# 자료의 차분 ---------- \033[0m", '\n')
cat(" dlog(df) ", '\n')
cat(" diff(log(df), lag=12) ", '\n')
cat(" diff(diff(log(df), lag=12)) ", '\n')
cat("\033[1;32m# ------------------- \033[0m", '\n')
cat("     ", '\n')
cat(" df<-openxlsx(GDPdata.xlsx) ", '\n')
cat(" gdp_sa<-ts(df$gdp_sa, start=c(1960,1), frequency=4) ", '\n')
cat(" # 참고: gdp_sa2<-window(gdp_sa, start=c(1980,1), end=c(2010,12), frequency=4) ", '\n')
cat(" plot(gdp_sa) ", '\n')
cat(" # plot을 보니, 1960년대를 전후로 나눌 필요가 있음 ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" e_sbreak() ", '\n')
cat(" library(strucchange);library(changepoint); library(tidyverse); library(lubridate) ", '\n')
cat(" Result02 <- cpt.meanvar(dlog(gdp_sa), method = 'PELT') ", '\n')
cat(" plot(Result02)  \033[1;32m# plot을 확인한 결과, 2020년대 이후자료만 고려하기로 \033[0m", '\n')
cat(" gdp_sa2<-window(gdp_sa, start=c(2000,1), frequency=4) ", '\n')
cat(" plot(gdp_sa) ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" identt(gdp_sa2) ", '\n')
cat(" ndiffs(gdp_sa2) ", '\n')
cat(" 1차 difference를 해야 stationary가 됨 ", '\n')
cat(" graphics.off() ", '\n')
cat(" plot(diff(gdp_sa2)) ", '\n')
cat(" identt(diff(gdp_sa2), 33) ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" summary(Arima(gdp_sa2,order=c(1,1,0),include.drift=T,method='ML') ) ", '\n')
cat(" summary(Arima(gdp_sa2, order=c(0,1,1), seasonal=c(0,0,2),include.drift=T, method='ML')) ", '\n')
cat(" summary(Arima(gdp_sa2,order=c(0,1,1),seasonal=c(0,0,2),fixed=c(NA,0,NA,NA), ", '\n')
cat(" include.drift=T,method='ML')) ", '\n')
cat(" ## include.drift=데이터가 차분된 경우 사용, include.mean=데이터 차분이 없을 경우 ", '\n')
cat(" 			 ", '\n')
cat(" summary(auto.arima(gdp_sa2, method='ML')) ", '\n')
cat("\033[1;33m# Eviews의 결과 형식과 R의 결과 형식은 동일함 \033[0m", '\n')
cat("\033[1;33m# Eviews와 동일한 방법으로 모형의 기록/해석 가능 \033[0m", '\n')
cat(" R1<-Arima( (gdp_sa2), order=c(1,1,1), method='ML')  ", '\n')
cat(" checkresiduals(R1)  ", '\n')
cat(" qstat(R1$resid)  ", '\n')
cat(" forecast(R1, h=5)  ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" R2 <- Arima( log(gdp_sa), order=c(1,1,1), ", '\n')
cat("              seasonal=c(2,1,1), fixed=c(NA,NA,0,NA,NA) , method='CSS' )  ", '\n')
cat(" R3 <- auto.arima( gdp_sa2, seasonal=FALSE, method='ML' )  ", '\n')
cat(" 			 ", '\n')
cat("\033[1;33m# Including exogenous variable & Seasonal data & Dummy variable---------- \033[0m", '\n')
cat(" dummy <- rep(0, 96); dummy[60:96] <- 1  ", '\n')
cat(" R4<- Arima( log(jeju), order=c(0,1,1),   ", '\n')
cat("      seasonal=list(order=c(0,1,2), period=12),   ", '\n')
cat("      include.mean=T, xreg=dummy, method='ML')  ", '\n')
cat(" Areport(R4)  ", '\n')
cat("\033[1;33m# R4 분석과 동일한 분석 --------------------  \033[0m", '\n')
cat("\033[1;33m# R5의 자료는 차분한 자료 및 차분 자료에 매칭되는 더미변수 사용 ----------------  \033[0m", '\n')
cat(" dummy <- rep(0, 83); dummy[60:83] <- 1  ", '\n')
cat(" R5<- Arima( diff(diff(log(jeju), lag=12)), order=c(0,0,1),   ", '\n')
cat("      seasonal=list(order=c(0,0,2), period=12),   ", '\n')
cat("      xreg=dummy, include.mean=T, method='ML' )  ", '\n')
cat(" Areport(R5)  ", '\n')
cat(" # --------------------  ", '\n')
cat(" simul <- arima.sim(model=list(order=c(2,0,2), ar=c(0.7,-0.6), ma=c(0.3,-0.5)),n=300) ", '\n')
cat(" 			 ", '\n')
}}
