# e_arima()

e_arima<-function(explaining=0){
if(explaining==0) {
cat("\033[1;33m# 자료의 차분 ---------- \033[0m", '\n')
cat(" dlog(df) ", '\n')
cat(" diff(log(df), lag=12) ", '\n')
cat(" diff(diff(log(df), lag=12)) ", '\n')
cat("\033[1;33m# ------------------- \033[0m", '\n')
cat("     ", '\n')
cat(" library(aj412s2);library(aj412ts) ", '\n')
cat(" library(forecast);library(ggfortify) ", '\n')
cat(" library(strucchange);library(changepoint) ", '\n')
cat("     ", '\n')
cat(" gdp<-gdp_sa$gdp_sa ", '\n')
cat(" gdp<-ts(gdp, start=c(1960,1), frequency=4) ", '\n')
cat(" plot(gdp) ", '\n')
cat("    ", '\n')
cat(" library(forecast) ", '\n')
cat(" ggsubseriesplot(gdp) ", '\n')
cat(" ggseasonplot(gdp, year.labels=T, year.labels.left=T)  ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" e_sbreak() ", '\n')
cat(" library(changepoint) ", '\n')
cat(" result <- cpt.meanvar(dlog(gdp), method = 'PELT') ", '\n')
cat(" plot(result)  \033[1;32m# plot을 확인한 결과, 1992년대 이후자료만 고려하기로 \033[0m", '\n')
cat(" 			 ", '\n')
cat("\033[1;32m# 1992년대를 후반 데이터만 추출 ---------- \033[0m", '\n')
cat(" gdp<-window(gdp, start=c(1992,1), end=c(2016,2)) ", '\n')
cat(" graphics.off() ", '\n')
cat(" plot(gdp) ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" identt(gdp) ", '\n')
cat(" ndiffs(gdp) ", '\n')
cat(" plot(dlog(gdp)) ", '\n')
cat(" identt(dlog(gdp), 33) ", '\n')
cat("\033[1;33m# 1차 difference를 해야 stationary가 됨 ---------- \033[0m", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" summary(Arima(gdp, order=c(1,1,0), include.drift=T) ) ", '\n')
cat(" summary(Arima(gdp, order=c(0,1,1), seasonal=c(0,0,2), include.drift=T)) ", '\n')
cat(" summary(Arima(gdp,order=c(0,1,1), seasonal=c(0,0,2), fixed=c(NA,0,NA,NA), ", '\n')
cat(" include.drift=T, method='CSS-ML')) ", '\n')
cat("\033[1;33m# include.drift=데이터가 차분된 경우 사용, include.mean=데이터 차분이 없을 경우 --- \033[0m", '\n')
cat("  ", '\n')
cat("\033[1;33m# 차분이 2회 이상 발생하면 - seasonal difference 포함 - drift가 포함하지 않는다 --- \033[0m", '\n')
cat(" 			 ", '\n')
cat(" auto.arima(gdp, method='CSS-ML') ", '\n')
cat(" auto.arima( gdp, seasonal=TRUE, optim.method='BFGS') ", '\n')
cat("\033[1;33m# auto.arima는 CSS-ML을 사용하고, Eviews는 ML을 사용함 \033[0m", '\n')
cat("\033[1;33m# 분석방법에 따라 결과 차이가 발생할 수 있음 \033[0m", '\n')
cat("\033[1;33m# Eviews의 결과 형식과 R의 결과 형식은 동일함 \033[0m", '\n')
cat("\033[1;33m# Eviews와 동일한 방법으로 모형의 기록/해석 가능 \033[0m", '\n')
cat(" R1<-Arima( log(gdp), order=c(1,1,1), method='CSS-ML', optim.method='Nelder-Mead')  ", '\n')
cat(" Areport(R1)  ", '\n')
cat(" summary(R1)  ", '\n')
cat(" checkresiduals(R1)  ", '\n')
cat(" qstat(R1$resid)  ", '\n')
cat(" forecast(R1, h=5)  ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" R2 <- Arima( log(gdp), order=c(1,1,1), ", '\n')
cat("              seasonal=c(2,1,1), fixed=c(NA,NA,0,NA,NA) , method='CSS-ML' )  ", '\n')
cat(" R3 <- auto.arima( gdp, seasonal=FALSE, method='CSS-ML' )  ", '\n')
cat(" 			 ", '\n')
cat("\033[1;33m# Including exogenous variable & Seasonal data & Dummy variable ---------- \033[0m", '\n')
cat("\033[1;33m# difference(차분)이 2회 이상 실행되면 include.drift는 사용 불가능 ---------- \033[0m", '\n')
cat(" dummy <- rep(0, 96); dummy[60:96] <- 1  ", '\n')
cat(" R4<- Arima( log(gdp), order=c(0,1,1),   ", '\n')
cat("      seasonal=list(order=c(0,1,2), period=12),   ", '\n')
cat("      xreg=dummy, method='CSS-ML')  ", '\n')
cat(" Areport(R4)  ", '\n')
cat("\033[1;33m# R4 분석과 동일하지만, 계수 제약이 있음 --------------------  \033[0m", '\n')
cat("\033[1;33m# R5의 자료는 차분한 자료 및 차분 자료에 매칭되는 더미변수 사용 ----------------  \033[0m", '\n')
cat(" dummy <- rep(0, 86); dummy[60:86] <- 1  ", '\n')
cat(" R5<- Arima( log(gdp), order=c(0,1,1),   ", '\n')
cat("      seasonal=list(order=c(0,1,2), period=12),   ", '\n')
cat("      fixed=c(NA,0,NA,NA),  ", '\n')
cat("      xreg=dummy, method='CSS-ML' )  ", '\n')
cat(" Areport(R5)  ", '\n')
cat(" 			 ", '\n')
cat("\033[1;33m# Simulation ---------- \033[0m", '\n')
cat(" simul <- arima.sim(model=list(order=c(2,0,2), ar=c(0.7,-0.6), ma=c(0.3,-0.5)),n=300) ", '\n')
cat(" 			 ", '\n')
cat("\033[1;33m# ARIMA결과 기록 ---------- \033[0m", '\n')
cat(" Const: 0.044 , AR(1): 0.559, AR(2): 0.137, MA(1): -0.234, MA(2): -0.472 ", '\n')
cat(" (1-0.559B - 0.137B^2 ) (▽Yt - 0.044 ) = ( 1-0.234B - 0.472B^2 )*et ", '\n')
cat(" ▽Yt = 0.044 + ( 1-0.234B - 0.472B^2  ) / (1-0.559B - 0.137B^2 )*et ", '\n')
cat(" 			 ", '\n')
}}
