# e_arima()

e_arima<-function(explaining=0){
if(explaining==0) {
cat(" library(readxl);library(forecast);library(strucchange);library(changepoint);library(r412ts) ", '\n')
cat(" df<-read_excel('GDPdata.xlsx') ", '\n')
cat(" gdp_sa<-ts(df$gdp_sa, start=c(1960,1), frequency=4) ", '\n')
cat(" 참고: gdp_sa2<-window(gdp_sa, start=c(1980,1), end=c(2010,12), frequency=4) ", '\n')
cat(" plot(gdp_sa) ", '\n')
cat(" plot을 보니, 1960년대 이후자료라서 자료를 나누는 것을 고려 ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" e_structuralbreak(0) ", '\n')
cat(" library(strucchange);library(changepoint); library(tidyverse); library(lubridate) ", '\n')
cat(" Result02 <- cpt.meanvar(dlog(gdp_sa), method = 'PELT') ", '\n')
cat(" plot(Result02) # plot을 확인한 결과, 2020년대 이후자료만 고려하기로 ", '\n')
cat(" gdp_sa2<-window(gdp_sa, start=c(2000,1), frequency=4) ", '\n')
cat(" plot(gdp_sa) ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" identt(gdp_sa2) ", '\n')
cat(" ndiffs(gdp_sa2) ", '\n')
cat(" 1차 difference를 해야 stationary가 됨 ", '\n')
cat(" graphics.off() ", '\n')
cat(" plot(diff(gdp_sa2)) ", '\n')
cat(" identt(diff(gdp_sa2), 33) ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat(" summary(Arima(gdp_sa2,order=c(1,1,0),include.drift=T,method='ML') ) ", '\n')
cat(" summary(Arima(gdp_sa2, order=c(0,1,1), seasonal=c(0,0,2),include.drift=T, method='ML')) ", '\n')
cat(" summary(Arima(gdp_sa2,order=c(0,1,1),seasonal=c(0,0,2),fixed=c(NA,0,NA,NA),include.drift=T,method='ML')) ", '\n')
cat(" 			 ", '\n')
cat(" summary(auto.arima(gdp_sa2, method='ML')) ", '\n')
cat(" Eviews의 결과 형식과 R의 결과 형식은 동일함. 동일한 방법으로 모형의 기록/해석 가능 ", '\n')
cat(" R1<-Arima( (gdp_sa2), order=c(1,1,1), method='ML')  ", '\n')
cat(" checkresiduals(R1)  ", '\n')
cat(" qstat(R1$resid)  ", '\n')
cat(" forecast(R1, h=5)  ", '\n')
cat(" 			 ", '\n')
cat(" R2 <- Arima( log(gdp_sa), order=c(1,1,1), ", '\n')
cat("              seasonal=c(2,1,1), fixed=c(NA,NA,0,NA,NA) , method='CSS' )  ", '\n')
cat(" R3 <- Arima( gdp_sa, order=c(1,1,1), seasonal=c(1,1,1), include.constant=T, method='CSS') ", '\n')
cat(" R4 <- auto.arima( gdp_sa2, seasonal=FALSE, method='ML' )  ", '\n')
cat(" simul <- arima.sim(model=list(order=c(2,0,2), ar=c(0.7,-0.6), ma=c(0.3,-0.5)),n=300) ", '\n')
cat(" 			 ", '\n')
}}
