e_BETA<-function(explaining=0){
if(explaining==0) {
cat(" library(quantmod)", '\n')
cat(" sdate <- as.Date('2015-01-05')", '\n')
cat(" edate <-as.Date('2022-08-24')", '\n')
cat(" Price=getSymbols('^GSPC', from=sdate, to=edate, auto.assign=F)", '\n')
cat(" R <- dailyReturn(Price[,4])", '\n')
cat(" ", '\n')
cat(" ## 25 day - Moving Average and 25-day Volatility(sd) -------------", '\n')
cat(" R_ma <- rollapply(R,25,mean)", '\n')
cat(" R_mv <- rollapply(R,25,sd)", '\n')
cat(" Price2 <- getSymbols('AAPL', from=sdate, to=edate, auto.assign=F)  ", '\n')
cat(" R2 <- dailyReturn(Price2[,4])", '\n')
cat(" R12 <- merge(R,R2)", '\n')
cat(" ", '\n')
cat(" # 50day BETA and 250day BETA ------------ ", '\n')
cat(" Beta <- rollapply(R12, 50, by.column = F, function(x) lm(x[,2] ~ x[,1])[[1]][[2]] )", '\n')
cat(" Beta <- rollapply(R12, 250, by.column = F, function(x) lm(x[,2] ~ x[,1])[[1]][[2]] )", '\n')
cat(" plot(Beta)", '\n')
}}
