# e_ca.jo()

e_coint<-function(explaining=0){
if(explaining==0) {
cat("  ", '\n')
cat("# 공적분(Cointegration) ------------------- ", '\n')
cat(" ca.jo() 함수는 Johansen 공적분 테스트(Johansen Cointegration Test)를  ", '\n')
cat(" 사용하여 시계열 데이터에서 공적분 관계를 확인하는 데 사용됩니다.  ", '\n')
cat(" 이 함수는 urca 패키지에서 사용할 수 있습니다. ca.jo() 함수에서  ", '\n')
cat(" eigen과 trace 옵션은 Johansen 공적분 테스트에서 cointegration rank를  ", '\n')
cat(" 선택하는 데 사용됩니다. ", '\n')
cat("  ", '\n')
cat(" eigen: 고유값(eigenvalue)을 사용하여 cointegration rank를 선택합니다. ", '\n')
cat(" trace: 고유값의 합(trace)을 사용하여 cointegration rank를 선택합니다. ", '\n')
cat(" eigen 및 trace 중 하나를 선택하여 Johansen 공적분 테스트를 수행합니다.  ", '\n')
cat("  ", '\n')
cat(" 두 옵션 중 어떤 것을 선택할지는 분석자의 판단에 따라 결정됩니다.  ", '\n')
cat(" 일반적으로 trace 옵션은 데이터가 작은 경우에 유용합니다. ", '\n')
cat(" 반면에 eigen 옵션은 데이터가 큰 경우에 더 적합합니다. ", '\n')
cat("  ", '\n')
cat(" 아래는 ca.jo() 함수에서 eigen 및 trace 옵션을 사용하여  ", '\n')
cat(" Johansen 공적분 테스트를 수행하는 예제 코드입니다. ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat(" library(urca) ", '\n')
cat("  ", '\n')
cat(" # 데이터 로드 ", '\n')
cat(" data('cointReg') ", '\n')
cat(" # Johansen 공적분 테스트 수행 ---------- ", '\n')
cat("   eigen_result <- ca.jo(cointReg, type = 'eigen', ecdet = 'const', K = 2) ", '\n')
cat("   trace_result <- ca.jo(cointReg, type = 'trace', ecdet = 'const', K = 2) ", '\n')
cat(" # 결과 출력 ", '\n')
cat("   summary(eigen_result) ", '\n')
cat("   summary(trace_result) ", '\n')
cat("  ", '\n')
cat(" 위 코드에서 type 옵션은 Johansen 공적분 테스트에서 사용할 eigen 또는 trace 방법을 선택합니다.  ", '\n')
cat(" ecdet 옵션은 추세 항을 지정하는 데 사용됩니다.  ", '\n')
cat(" K 옵션은 cointegration rank의 최대값을 지정합니다.  ", '\n')
cat(" 위 코드에서는 K = 2로 설정하여 최대 cointegration rank가 2인 경우를 고려합니다. ", '\n')
cat("  ", '\n')
cat(" ca.jo() 함수에서 ecdet 옵션은 추세 항(trend)을 지정하는 데 사용됩니다.  ", '\n')
cat(" 이 옵션은 공적분 검정을 수행하기 전에 각 시계열에 대한 추세 항을 지정하는 데 사용됩니다.  ", '\n')
cat(" ecdet 옵션은 다음과 같은 값을 가질 수 있습니다. ", '\n')
cat("  ", '\n')
cat(" 'none': 추세 항을 사용하지 않습니다. ", '\n')
cat(" 'const': 상수 추세 항을 사용합니다. ", '\n')
cat(" 'trend': 선형 추세 항을 사용합니다. ", '\n')
cat(" 'both': 상수 및 선형 추세 항을 사용합니다. ", '\n')
cat(" 보통 ecdet 옵션은 const 값으로 설정하는 것이 일반적입니다.  ", '\n')
cat(" 이는 데이터에서 관측된 추세가 상수임을 가정하기 때문입니다.  ", '\n')
cat(" 하지만 경우에 따라 추세가 선형적으로 증가하거나 감소하는 경우도 있을 수 있습니다.  ", '\n')
cat(" 이 경우에는 trend 또는 both 값을 사용하여 선형 추세 항을 추가할 수 있습니다. ", '\n')

}}
