#e_ecos

e_ecos<-function(explaining=0){
if(explaining==0) {
cat("    ", '\n')
cat("#------------------------------------------------------ ", '\n')
cat("    ", '\n')
cat("# apkey 다운로드 받는 곳 ", '\n')
cat("# https://ecos.bok.or.kr/api/#/AuthKeyApply ", '\n')
cat("  ", '\n')
cat("# ECOS자료 Code Book ", '\n')
cat("# https://ecos.bok.or.kr/api/#/DevGuide/StatisticalCodeSearch ", '\n')
cat("  ", '\n')
cat(" library(ecos); library(dplyr); library(quantmod); library(lubridate)", '\n')
cat(" library(xts); library(mFilter)", '\n')
cat(" ecos.setKey(api_key = 'PDAG09WXHMB9IJ1RNMGX') ", '\n')
cat(" sdate <- as.Date('2018-01-01') ", '\n')
cat(" edate <- as.Date('2024-07-31') ", '\n')
cat("    ", '\n')
cat("# create Time Series Objects ------------- ", '\n')
cat("  gdp<-statSearch(stat_code='200Y004', item_code1='1400', cycle='Q')   ", '\n')
cat("  gdp<-gdp[,c(14)]   ", '\n')
cat("  gold <- ts(gdp ,start=c(1960, 1), frequency=4)  ", '\n')
cat("    ", '\n')
cat("# xts의 apply.quarterly() 사용 ------------- ", '\n')
cat(" \033[1;32m 자료1<-xts(전산업생산지수$ind_m, order.by=전산업생산지수$date)   \033[0m ", '\n')
cat(" \033[1;32m NOTE: 전산업생산지수$date의 형태 = 2020-04-01  ", '\n')
cat(" \033[1;32m 자료2<-apply.quarterly(자료1, FUN=colMeans)  \033[0m ", '\n')
cat("    ", '\n')
cat("# xts를 ts로 전환 ------------- ", '\n')
cat("  library(dsa)  ", '\n')
cat("  tmp <- xts2ts(xtsdata)  ", '\n')
cat("    ", '\n')
cat(" gdp<-statSearch(stat_code='200Y004', item_code1='1400', cycle='Q')", '\n')
cat("# 경제성장률(분기별 gdp) ------------- ", '\n')
cat(" \033[1;32m 전년동기대비_GDP성장률 <- (gdp / dplyr::lag(gdp, 4) -1 )*100    \033[0m ", '\n')
cat("   ", '\n')
cat("# 또는 다른 방법은 ...   ", '\n')
cat(" \033[1;32m YoY_changes <- diff(Adata$data_value, lag = 12) \033[0m ", '\n')
cat(" \033[1;32m YoY_changes 계산방법 = {24년1월-23년1월, 24년2월-23년2월, ... , 24년12월-23년12월} \033[0m ", '\n')
cat(" \033[1;32m 변화율_계산 = { YoY_changes/Adata$data_value[1:(자료수-12)] }   \033[0m ", '\n')
cat(" \033[1;32m YoY_changes2<-ts(변화율_계산, start=c(1966,1), f=12) \033[0m  ", '\n')
cat(" df<-window(YoY_changes2, start=c(2000,1) ) ", '\n')
cat(" plot(df) ", '\n')
cat(" library(ggfortify) ", '\n')
cat(" autoplot(df) ", '\n')
cat(" ggsubseriesplot(df) ", '\n')
cat(" ggseasonplot(df) ", '\n')
cat("  ", '\n')
cat("  ", '\n')
cat(" 소비자물가지수<-statSearch(stat_code='901Y009', item_code1='0', cycle='M')  ", '\n')
cat(" 전산업생산지수<-statSearch(stat_code='901Y033', item_code1='A00', item_code2='2', cycle='M') ", '\n')
cat(" 전산업생산지수<-전산업생산지수%>%select(time, data_value)%>%mutate(time=ym(time)) ", '\n')
cat(" names(전산업생산지수)<-c('date', 'ind_m') ", '\n')
cat(" 전산업생산지수<-xts(전산업생산지수$ind_m, order.by=전산업생산지수$date) ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat(" # 기업경영분석: 대기업/2009~2021년/현금및현금성자산비율 ---", '\n')
cat(" 현금및현금성자산비율 <-statSearch(stat_code='501Y007', item_code1='ZZZ00', item_code2='L', item_code3='7041', cycle='A')", '\n')
cat(" 분기별콜금리<-statSearch(stat_code='721Y001', item_code1='1020000', cycle='Q') ", '\n')
cat(" 월별소비자물가지수<-statSearch(stat_code='901Y009',item_code1='0',cycle='M') ", '\n')
cat(" 전년동기대비인플레이션 <- 100*(tscpi_m/stats::lag(tscpi_m, 12) -1 ) ", '\n')
cat(" M2평잔<-statSearch(stat_code='101Y003', item_code1='BBHS00', item_code2='2', cycle='M') ", '\n')
cat(" 경상수지<-statSearch(stat_code='301Y013', item_code1='000000', item_code2='2', cycle='M') ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat(" 상해지수<-getSymbols('000001.ss', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 선전지수<-getSymbols('399001.SZ', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 홍콩항생지수<-getSymbols('^HSI', from=sdate, to=edate,	auto.assign=F) ", '\n')
cat("  ", '\n')
cat(" 테슬라=getSymbols('TSLA', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 애플=getSymbols('AAPL', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 삼성=getSymbols('005930.KS', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 삼성<-삼성[,4] ", '\n')
cat(" 현대=getSymbols('005380.KS', from=sdate, to=edate, auto.assign=F) ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat(" --- xts패키지내 apply.monthly(), apply.quarterly(), apply.year() --- ", '\n')
cat(" Adata월별자료 <- apply.monthly(Adata, mean) ", '\n')
cat(" ---- stargazer 사용하기  ", '\n')
cat(" stargazer(결과, type='html', out='결과.doc') ", '\n')
}}
