#e_ecos

e_ecos<-function(explaining=0){
if(explaining==0) {
cat('\014')
cat("#------------------------------------------------------ ", '\n')
cat("    ", '\n')
cat("# apkey 다운로드 받는 곳 ", '\n')
cat("# https://ecos.bok.or.kr/api/#/AuthKeyApply ", '\n')
cat("  ", '\n')
cat("# ECOS자료 Code Book ", '\n')
cat("  https://ecos.bok.or.kr/api/#/DevGuide/StatisticalCodeSearch ", '\n')
cat("  ", '\n')
cat(" library(ecos); library(dplyr); library(quantmod); library(lubridate)", '\n')
cat(" library(xts); library(mFilter)", '\n')
cat(" ecos.setKey(api_key = 'PDAG09WXHMB9IJ1RNMGX') ", '\n')
cat(" sdate <- as.Date('2018-01-01') ", '\n')
cat(" edate <- as.Date('2024-07-31') ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat('\014')
cat("    ", '\n')
cat("\033[1;32mCreate Time Series Objects ------------- \033[0m ", '\n')
cat(" gdp <- statSearch(stat_code='200Y004', item_code1='1400', cycle='Q')   ", '\n')
cat(" 현금성자산비율 <- statSearch(stat_code='501Y007', item_code1='ZZZ00', item_code2='L', item_code3='7041', cycle='A')", '\n')
cat(" Call금리 <- statSearch(stat_code='721Y001', item_code1='1020000', cycle='Q') ", '\n')
cat(" 월별소비자물가지수 <- statSearch(stat_code='901Y009',item_code1='0',cycle='M') ", '\n')
cat(" 전년동기대비인플레이션 <- 100*(tscpi_m/stats::lag(tscpi_m, 12) -1 ) ", '\n')
cat(" M2평잔 <- statSearch(stat_code='101Y003', item_code1='BBHS00', item_code2='2', cycle='M') ", '\n')
cat(" 경상수지 <- statSearch(stat_code='301Y013', item_code1='000000', item_code2='2', cycle='M') ", '\n')
cat(" 소비자물가지수 <- statSearch(stat_code='901Y009', item_code1='0', cycle='M')  ", '\n')
cat(" 전산업생산지수 <- statSearch(stat_code='901Y033', item_code1='A00', item_code2='2', cycle='M') ", '\n')
cat("  ", '\n')
cat("\033[1;31m전산업생산지수를 xts 그래프로 보기 ----------- \033[0m ", '\n')
cat(" 전산업생산지수 <- ecos_simple(전산업생산지수, '2015') ", '\n')
cat("\033[1;32m# ecos_simple()을 사용하면 데이터셋의 data가 전산업생산지수. yoy, %yoy도 데이터셋에 저장됨 \033[0m ", '\n')
cat(" tmp_data <- xts(전산업생산지수$data, order.by=전산업생산지수$DATE) ", '\n')
cat(" plot(tmp_data, main = '월별자료', col = 'blue') ", '\n')
cat("\033[1;31m전산업생산지수를 ggplot2 그래프로 보기 ----------- \033[0m ", '\n')
cat(" ggplot(전산업생산지수, aes(x=DATE, y=data)) + geom_line() + theme_bw() ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat('\014')
cat("    ", '\n')
cat("\033[1;32m경제지수 및 주가 ----------- \033[0m ", '\n')
cat(" 상해지수 <- getSymbols('000001.ss', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 선전지수 <- getSymbols('399001.SZ', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 홍콩항생지수 <- getSymbols('^HSI', from=sdate, to=edate,	auto.assign=F) ", '\n')
cat(" 테슬라 <- getSymbols('TSLA', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 애플 <- getSymbols('AAPL', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 삼성 <- getSymbols('005930.KS', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 현대 <- getSymbols('005380.KS', from=sdate, to=edate, auto.assign=F) ", '\n')
cat("  ", '\n')
cat(" autoplot(상해지수[, '000001.SS.Close']) ", '\n')
cat(" autoplot(테슬라[,'TSLA.Close']) ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat('\014')
cat("    ", '\n')
cat("\033[1;31m# xts패키지: apply.monthly(), apply.quarterly(), apply.year() --- ", '\n')
cat("\033[1;32m# xts의 apply.quarterly() 사용예제 ------------- \033[0m  ", '\n')
cat(" 전산업생산지수 <- ecos_simple(전산업생산지수, '2015') # Monthly자료를 Quarterly자료로 전환하자", '\n')
cat(" TMP <- xts(전산업생산지수$data, order.by=전산업생산지수$DATE) ", '\n')
cat(" 전산업생산지수 자료는 \033[1;31m'전산업생산지수$data'\033[0m   ", '\n')
cat(" apply.yearly( TMP[, 1], FUN=colMeans ) ", '\n')
cat("    ", '\n')
cat("\033[1;32m# xts를 ts로 전환 -------------   \033[0m", '\n')
cat("  library(dsa)  ", '\n')
cat("  tmp <- xts2ts(xtsdata)  ", '\n')
cat("    ", '\n')

}}
