#e_ecos

e_ecos<-function(explaining=0){
if(explaining==0) {
cat("    ", '\n')
cat("#------------------------------------------------------ ", '\n')
cat("    ", '\n')
cat("# ECOS자료 Code Book ", '\n')
cat("# https://ecos.bok.or.kr/api/#/DevGuide/StatisticalCodeSearch ", '\n')
cat("  ", '\n')
cat("# apkey 다운로드 받는 곳 ", '\n')
cat("# https://ecos.bok.or.kr/api/#/AuthKeyApply ", '\n')
cat("  ", '\n')
cat(" library(ecos); library(xts); library(quantmod); library(xts); library(lubridate)  ; library(dplyr); library(mFilter)", '\n')
cat(" my_key<-c('PDAG09WXHMB9IJ1RNMGX') ", '\n')
cat(" sdate <- as.Date('2015-01-05') ", '\n')
cat(" edate <-as.Date('2022-09-04') ", '\n')
cat("  ", '\n')
cat(" 전산업생산지수<-statSearch(api_key=my_key, stat_code='901Y033', item_code1='A00', item_code2='2', cycle='M') ", '\n')
cat(" 전산업생산지수<-전산업생산지수%>%select(time, data_value)%>%mutate(time=ym(time)) ", '\n')
cat(" names(전산업생산지수)<-c('date', 'ind_m') ", '\n')
cat(" 전산업생산지수<-xts(전산업생산지수$ind_m, order.by=전산업생산지수$date) ", '\n')
cat("  ", '\n')
cat(" gdp<-statSearch(api_key=my_key, stat_code='200Y004', item_code1='1400', cycle='Q')   ", '\n')
cat(" gdp<-gdp%>%select(time, data_value)%>%mutate(time=ym(time))   ", '\n')
cat(" names(gdp)<-c('date', 'gdpdata')   ", '\n')
cat(" rownames(gdp)<-c() ", '\n')
cat(" ## gdp자료를 이동평균으로 smoothing 시키는 작업 생략함. 추후 추가할 것 ", '\n')
cat(" gdp<-ts(gdp$gdpdata, start=c(2005,1), freq=4) ", '\n')
cat(" gdp2<-decompose(gdp) ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat(" 분기별콜금리<-statSearch(api_key=my_key, stat_code='721Y001', item_code1='1020000', cycle='Q') ", '\n')
cat(" 분기별콜금리<-분기별콜금리%>%select(time, data_value)%>%mutate(time=yq(time)) ", '\n')
cat(" names(분기별콜금리)<-c('date', 'call_q') ", '\n')
cat("  ", '\n')
cat(" 월별소비자물가지수<-statSearch(api_key=my_key,stat_code='901Y009',item_code1='0',cycle='M') ", '\n')
cat(" 월별소비자물가지수<-월별소비자물가지수%>%select(time, data_value)%>%mutate(time=ym(time)) ", '\n')
cat(" names(월별소비자물가지수)<-c('date', 'cpi_m') ", '\n')
cat(" tscpi_m <- xts(월별소비자물가지수$cpi_m, order.by=월별소비자물가지수$date) ", '\n')
cat("  ", '\n')
cat(" 전년동기대비인플레이션 <- 100*(tscpi_m/stats::lag(tscpi_m, 12) -1 ) ", '\n')
cat("  ", '\n')
cat(" M2평잔<-statSearch(api_key=my_key, stat_code='101Y003', item_code1='BBHS00', item_code2='2', cycle='M') ", '\n')
cat(" M2평잔<-M2평잔%>%select(time, data_value)%>%mutate(time=ym(time)) ", '\n')
cat(" names(M2평잔)<-c('date', 'M2_m') ", '\n')
cat("  ", '\n')
cat(" 경상수지<-statSearch(api_key=my_key, stat_code='301Y013', item_code1='000000', item_code2='2', cycle='M') ", '\n')
cat(" 경상수지<-경상수지%>%select(time, data_value)%>%mutate(time=ym(time)) ", '\n')
cat(" names(경상수지)<-c('date', '경상수지') ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat(" 상해지수<-getSymbols('000001.ss', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 선전지수<-getSymbols('399001.SZ', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 홍콩항생지수<-getSymbols('^HSI', from=sdate, to=edate,	auto.assign=F) ", '\n')
cat("  ", '\n')
cat(" 테슬라=getSymbols('TSLA', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 테슬라<-테슬라[,4] ", '\n')
cat(" names(테슬라) <- c('tesla') ", '\n')
cat("  ", '\n')
cat(" 애플=getSymbols('AAPL', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 애플<-애플[,4] ", '\n')
cat(" names(애플) <- c('apple') ", '\n')
cat("  ", '\n')
cat(" 삼성=getSymbols('005930.KS', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 삼성<-삼성[,4] ", '\n')
cat(" names(삼성) <- c('samsung') ", '\n')
cat("  ", '\n')
cat(" 현대=getSymbols('005380.KS', from=sdate, to=edate, auto.assign=F) ", '\n')
cat(" 현대<-현대[,4] ", '\n')
cat(" names(현대) <- c('hyundai') ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat(" --- xts패키지내 apply.monthly(), apply.quarterly(), apply.year() --- ", '\n')
cat(" Adata월별자료 <- apply.monthly(Adata, mean) ", '\n')
cat(" ---- stargazer 사용하기  ", '\n')
cat(" stargazer(결과, type='html', out='결과.doc') ", '\n')
}}
