# e_hpfilter

e_hpfilter<-function(explaining=0){
if(explaining==0) {
cat(" library(aj412ts) ", '\n')
cat("# 경제자료 분석시 월별/분기별 자료의 계절변동(seasonality)은 제거해야 함. 연가자료는 계절변동 없으므로 그대로 사용함.    ", '\n')
cat("# 방법1: seasonal패키지의 seasadj()=계절적으로 조정된 시계열 생성 ---------    ", '\n')
cat("  library(seasonal)  ", '\n')
cat("  gdp<-ts(eviews1[,'gdp'], start=c(1960,1), f=4)  ", '\n')
cat("  library(seasonal); library(forecast)  ", '\n')
cat("  fit<-gdp%>%seas(x11='')  ", '\n')
cat("  gdp_sa<-seasadj(fit)  ", '\n')
cat("    ", '\n')
cat("  autoplot(gdp_sa)  ", '\n')
cat("  ggsubseriesplot(gdp_sa)  ", '\n')
cat("  ggseasonplot(gdp_sa)  ", '\n')
cat("  ggseasonplot(gdp_sa, polar=T)  ", '\n')
cat("  # autoplot(elecdemand[,c('Demand', 'Temperature')], facets=T)  ", '\n')
cat("  # gplot(Temperature, Demand, data=as.data.frame(elecdemand))  ", '\n')
cat("    ", '\n')
cat("# gdp_sa데이터는 계절성을 제거한 시계열 -----------    ", '\n')
cat("# HP필터를 사용해 추세변동, 순환변동을 조사함 --------  ", '\n')
cat("  library(mFilter)   ", '\n')
cat("  HPgdp_sa <- hpfilter(gdp_sa,freq = 1600) ", '\n')
cat("  # NOTE: month=14400 / quarter=1600 / year=1000 ", '\n')
cat("  plot(HPgdp_sa) ", '\n')
cat("  plot(HPgdp_sa$cycle, type='l', lty='twodash', col='steelblue', lwd='2') ", '\n')
cat("    ", '\n')
cat("# 방법2: Moving Average function for 5-periods   ", '\n')
cat("# df_data=데이터프레임, ncolx=컬럼번호 -------------   ", '\n')
cat("data_5mv<-function(df_data, ncolx) {    ", '\n')
cat("   n<-nrow(df_data[ ,ncolx])   ", '\n')
cat("   gdp<-as.data.frame(df_data)   ", '\n')
cat("   tempx<-as.data.frame(gdp[, ncolx])    ", '\n')
cat("   colnames(tempx)<-'gdp' ", '\n')
cat("   tempx$tmp1 <- dplyr::lead(tempx$gdp, 1)     ", '\n')
cat("   tempx$tmp2 <- dplyr::lead(tempx$gdp, 2)    ", '\n')
cat("   tempx$tmp3 <- dplyr::lag(tempx$gdp, 1)    ", '\n')
cat("   tempx$tmp4 <- dplyr::lag(tempx$gdp, 2)    ", '\n')
cat("   gdp_5mv<-(0.25*0.5*tempx$tmp2+0.25*tempx$tmp1+0.25*tempx$gdp+0.25*tempx$tmp3+0.25*0.5*tempx$tmp4) ", '\n')
cat("   return(gdp_5mv)    ", '\n')
cat( " }    ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
cat( "# 방법3: data_5mv()는 forecast의 ma()와 동일한 명령문 ----------     ", '\n')
cat( "  library(forecast)     ", '\n')
cat( "  ma(df[,'gdp'], 4)     ", '\n')
cat(" 			 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 			 ", '\n')
}}
