# e_hpfilter

e_hpfilter<-function(explaining=0){
if(explaining==0) {
cat("  ", '\n')
cat("# 계절조정이 된 자료를 다운받아 사용할 경우, 필요없는 과정입니다^^ ", '\n')
cat("# 경제자료 분석시 월별/분기별 자료의 계절변동(seasonality)을 제거하는 방법 ", '\n')
cat("# 단, 연도별자료는 계절변동이 있을 수 없으므로 그대로 사용    ", '\n')
cat("# library(seasonal); library(forecast)", '\n')
cat("# fit <- gdp%>%seas(x11='')", '\n')
cat("# gdp_sa <- seasadj(fit)", '\n')
cat("  ", '\n')
cat("# devtools::install_github('ssbaj/aj412s')  ", '\n')
cat("# devtools::install_github('ssbaj/aj412ts')  ", '\n')
cat("   ", '\n')
cat("# apkey 다운로드 받는 곳 ", '\n')
cat("# https://ecos.bok.or.kr/api/#/AuthKeyApply ", '\n')
cat("  ", '\n')
cat("# ECOS자료 Code Book ", '\n')
cat("  https://ecos.bok.or.kr/api/#/DevGuide/StatisticalCodeSearch ", '\n')
cat("  ", '\n')
cat("library(aj412s); library(aj412ts); library(ecos); library(xts); library(dplyr)", '\n')
cat("ecos.setKey(api_key = '당신의 ECOS 등록key 입력하세요')", '\n')
cat("set_data<-c('PDAG09ELCA88WXHMB9IJ1RNMGXYULGOK412')", '\n')
cat("  ", '\n')
cat("gdp <- statSearch(stat_code='200Y104', item_code1='1400', cycle='Q')", '\n')
cat("gdp <- simple_ecos(gdp, '2014')", '\n')
cat("  ", '\n')
cat("# lambda값 설정: monthly=14400 / quarterly=1600 / year=100", '\n')
cat("  ", '\n')
cat("library(mFilter)", '\n')
cat("hp_gdp <- hpfilter(gdp$data, freq = 1600) ", '\n')
cat("hp_gdp <- data.frame( gdp$DATE, hp_gdp$trend, hp_gdp$cycle) ", '\n')
cat("colnames(hp_gdp) <- c('DATE', 'trend', 'cycle') ", '\n')
cat("hp_gdp$Q잠재성장률 <- (hp_gdp$trend - dplyr::lag(hp_gdp$trend) ) / dplyr::lag(hp_gdp$trend)", '\n')
cat("hp_gdp <- hp_gdp[-c(1), ]", '\n')
cat("plot(hp_gdp$DATE, hp_gdp$cycle, type='l', lty='twodash', col='steelblue', lwd='2') ", '\n')
cat("plot(hp_gdp$DATE, hp_gdp$trend, type='l', lty='dashed', col='salmon3', lwd='2') ", '\n')
cat("plot(hp_gdp$DATE, hp_gdp$Q잠재성장률, type='l', lty='solid', col='black', lwd='2') ", '\n')
cat("   ", '\n')
}}
