# e_hpfilter

e_hpfilter<-function(explaining=0){
if(explaining==0) {
cat("library(ecos); library(xts); library(quantmod); library(lubridate)  ; library(dplyr); library(mFilter)", '\n')
cat("ecos.setKey(api_key = 'LoveYourself') ", '\n')
cat("sdate <- as.Date('2018-01-01') ", '\n')
cat("edate <- as.Date('2024-09-30') ", '\n')
cat("  ", '\n')
cat("gdp<-statSearch(stat_code='200Y004', item_code1='1400', cycle='Q')", '\n')
cat("gdp<-gdp%>%select(time, data_value)%>%mutate(time=ym(time))", '\n')
cat("names(gdp)<-c('date', 'gdpdata')", '\n')
cat("rownames(gdp)<-c() ## rownames를 1,2,3,4 ... 순으로 만드는 명령문", '\n')
cat("gdp<-ts(gdp$gdpdata, start=c(1960,1), freq=4)  ## gdp자료를 4분기 계절자료로 지정", '\n')
cat("  ", '\n')
cat("# 경제자료 분석시 월별/분기별 자료의 계절변동(seasonality)은 제거해야 함 ", '\n')
cat("# 단, 연도별자료는 계절변동이 있을 수 없으므로 그대로 사용    ", '\n')
cat("library(seasonal); library(forecast)", '\n')
cat("fit<-gdp%>%seas(x11='')", '\n')
cat("gdp_sa<-seasadj(fit)", '\n')
cat("  ", '\n')
cat("autoplot(gdp_sa)", '\n')
cat("ggsubseriesplot(gdp_sa)", '\n')
cat("ggseasonplot(gdp_sa)", '\n')
cat("ggseasonplot(gdp_sa, polar=T)", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("  ", '\n')
cat("# 1960년 1분기 GDP부터 추세변동 조사 --------  ", '\n')
cat("library(mFilter)", '\n')
cat("HPgdp_sa <- hpfilter(gdp_sa,freq = 1600)", '\n')
cat("# NOTE: month=14400 / quarter=1600 / year=1000", '\n')
cat("plot(HPgdp_sa)", '\n')
cat("plot(HPgdp_sa$cycle, type='l', lty='twodash', col='steelblue', lwd='2') ", '\n')
cat("# 2000년 1분기 자료부터 추세변동/순환변동 조사 --------  ", '\n')
cat("gdp_sa2<-window(gdp_sa, start=c(2000,1), end=c(2023, 2))", '\n')
cat("HPgdp_sa2 <- hpfilter(gdp_sa2, freq = 1600)", '\n')
cat("plot(HPgdp_sa2$cycle, type='l', col='steelblue', lwd='2')", '\n')
cat("plot(HPgdp_sa2$trend, type='l', col='steelblue', lwd='2')", '\n')
cat("Example1 <- c(PDAG09) ", '\n')
cat("Example2 <- c(WXHMB9) ", '\n')
cat("Example3 <- c(IJ1RNMGX) ", '\n')
cat("   ", '\n')
}}
