#e_kosis

e_kosis<-function(explaining=0){
if(explaining==0) {
cat("    ", '\n')
cat("#------------------------------------------------------ ", '\n')
cat("    ", '\n')
cat("# apkey 다운로드 받는 곳 ", '\n')
cat("# https://kosis.kr/openapi/ ", '\n')
cat("  ", '\n')
cat("# KOSIS자료 Code Book ", '\n')
cat("# https://kosis.kr/openapi/devGuide/devGuide_0101List.do ", '\n')
cat("  ", '\n')
cat(" \033[1;32m 서비스뷰 코드(vwCd) \033[0m ", '\n')
cat(" \033[1;31m · MT_ZTITLE : 국내통계 주제별 \033[0m ", '\n')
cat(" \033[1;32m · MT_OTITLE : 국내통계 기관별 \033[0m ", '\n')
cat(" \033[1;32m · MT_GTITLE01 : e-지방지표(주제별) \033[0m ", '\n')
cat(" \033[1;32m · MT_GTITLE02 : e-지방지표(지역별) \033[0m ", '\n')
cat(" \033[1;32m · MT_CHOSUN_TITLE : 광복이전통계(1908~1943) \033[0m ", '\n')
cat(" \033[1;32m · MT_HANKUK_TITLE : 대한민국통계연감 \033[0m ", '\n')
cat(" \033[1;32m · MT_STOP_TITLE : 작성중지통계 \033[0m ", '\n')
cat(" \033[1;32m · MT_RTITLE : 국제통계 \033[0m ", '\n')
cat(" \033[1;32m · MT_BUKHAN : 북한통계 \033[0m ", '\n')
cat(" \033[1;32m · MT_TM1_TITLE : 대상별통계 \033[0m ", '\n')
cat(" \033[1;32m · MT_TM2_TITLE : 이슈별통계 \033[0m ", '\n')
cat(" \033[1;32m · MT_ETITLE : 영문 KOSIS \033[0m ", '\n')
cat("  ", '\n')
cat("library(kosis)", '\n')
cat("kosis.setKey('MDE3ZDM1M2Y0MWIxNzI5OGELCA88IzZGExNmM1NWIzNTNlMjA=')", '\n')
cat("topic<-getStatList(vwCd='\033[1;31mMT_ZTITLE\033[0m')", '\n')
cat("", '\n')
cat("topic_sub0<-getStatList(vwCd='\033[1;31mMT_ZTITLE\033[0m')", '\n')
cat("topic_sub1<-getStatList(vwCd='MT_ZTITLE', parentListId='S2')", '\n')
cat("topic_sub2<-getStatList(vwCd='MT_ZTITLE', parentListId='S2_11', )", '\n')
cat(" ", '\n')
cat("starttime<-'202401' ", '\n')
cat("endtime<-'202406' ", '\n')
cat(" ", '\n')
cat("# orgIds = 조직 ID ", '\n')
cat("# prdSe = 수록주기: D(일), M, Q, H(3월), Y(년) ", '\n')
cat(" ", '\n')
cat("# 전체국가 추출 ", '\n')
cat("data1<-getStatData(orgId='134', tblId='DT_134001_002', prdSe='M',  ", '\n')
cat("       startPrdDe=starttime, endPrdDe=endtime, objL1='All') ", '\n')
cat(" ", '\n')
cat("# 중국 추출 ", '\n')
cat("data2<-getStatData(orgId='134', tblId='DT_134001_002', prdSe='M',  ", '\n')
cat("       startPrdDe=starttime, endPrdDe=endtime, objL1='CN') ", '\n')
cat(" ", '\n')
cat("# 중국, 미국, 일본 추출 ", '\n')
cat("plist<-list() ", '\n')
cat("country<-c('CN', 'US', 'JP') ", '\n')
cat("for(i in country){ ", '\n')
cat("tmp<-getStatData(orgId='134', tblId='DT_134001_002', prdSe='M',  ", '\n')
cat("       startPrdDe=sper, endPrdDe=eper, objL1=i )  ", '\n')
cat("plist[[i]] <-tmp ", '\n')
cat(" } ", '\n')
cat("# plits에 중국, 미국, 일본 자료 저장 ", '\n')

}}
