#e_kosis

e_kosis<-function(explaining=0){
if(explaining==0) {
cat("    ", '\n')
cat("#------------------------------------------------------ ", '\n')
cat("    ", '\n')
cat("# apkey 다운로드 받는 곳 ", '\n')
cat("# https://kosis.kr/openapi/ ", '\n')
cat("# MDE3ZDM1M2Y0MWIxELCA999NzI5OGIzZGExShimBIX777NmM1NWIzNTNlMjA=   ", '\n')
cat("  ", '\n')
cat("# KOSIS자료 Code Book ", '\n')
cat("# https://kosis.kr/openapi/devGuide/devGuide_0101List.do ", '\n')
cat("  ", '\n')
cat("#------------------------------------------------------ ", '\n')
cat("    ", '\n')
cat("# orgIds = 조직 ID ", '\n')
cat("# prdSe = 수록주기: D(일), M, Q, H(3월), Y(년) ", '\n')
cat(" ", '\n')
cat(" kosis데이터 <- getStatData(   ", '\n')
cat("   orgId = '',  ", '\n')
cat("   tblId = '',  ", '\n')
cat("   prdSe = '',  ", '\n')
cat("   itmId = '',  ", '\n')
cat("   newEstPrdCnt = 숫자입력.따옴표 없음, ", '\n')
cat("   startPrdDe='', ", '\n')
cat("   endPrdDe='', ", '\n')
cat("   objL1='', ", '\n')
cat("   objL2='', ", '\n')
cat("   objL3='' ", '\n')
cat(" ) ", '\n')
cat("  ", '\n')
}}
