#e_kosis

e_kosis<-function(explaining=0){
if(explaining==0) {
cat("    ", '\n')
cat("#------------------------------------------------------ ", '\n')
cat("    ", '\n')
cat("# apkey 다운로드 받는 곳 ", '\n')
cat("# https://kosis.kr/openapi/ ", '\n')
cat("    ", '\n')
cat("# KOSIS자료 Code Book ", '\n')
cat("# https://kosis.kr/openapi/devGuide/devGuide_0101List.do ", '\n')
cat("  ", '\n')
cat("#------------------------------------------------------ ", '\n')
cat("    ", '\n')
cat("  library(kosis)  ", '\n')
cat("    ", '\n')
cat(" kosis.setKey(apiKey='당신의 API값을 입력하세요')   ", '\n')
cat("    ", '\n')
cat("# MDE3ZDM1M2Y0MWIxELCA999NzI5OGIzZGExShimBIX777NmM1NWIzNTNlMjA=   ", '\n')
cat("  ", '\n')
cat("# orgIds = 조직 ID ", '\n')
cat("# prdSe = 수록주기: D(일), M, Q, H(3월), Y(년) ", '\n')
cat(" ", '\n')
cat(" kosis데이터 <- getStatData(   ", '\n')
cat("   orgId = '',  ", '\n')
cat("   tblId = '',  ", '\n')
cat("   prdSe = '',  ", '\n')
cat("   itmId = '',  ", '\n')
cat("   newEstPrdCnt = 숫자입력.따옴표 없음, ", '\n')
cat("   startPrdDe='', ", '\n')
cat("   endPrdDe='', ", '\n')
cat("   objL1='', ", '\n')
cat("   objL2='', ", '\n')
cat("   objL3='' ", '\n')
cat(" ) ", '\n')
cat("  ## Data Format의 변경 -------------", '\n')
cat("  data<-data.frame(  ", '\n')
cat("  v1<-c('서울', '서울', '서울','서울', '서울', '서울'),  ", '\n')
cat("   v2<-c('노동','노동','노동', '광업','광업','광업'),  ", '\n')
cat("   v3<-c(2023, 2022, 2021,2023, 2022, 2021),  ", '\n')
cat("   v4<-c(33, 44, 55, 66, 88, 99)  ", '\n')
cat("   )  ", '\n')
cat("    ", '\n')
cat("  ## R을 사용해 위 데이터셋을 다음과 같이 재배열하는 명령문 --- ", '\n')
cat("  data<-data.frame(  ", '\n')
cat("  v1<-c('서울', '서울', '서울'),  ", '\n')
cat("  연도<-c(2023, 2022, 2021),  ", '\n')
cat("  노동<-c(33, 44, 55),  ", '\n')
cat("  광업<-c(66, 88, 99)  ", '\n')
cat("  )   ", '\n')
cat("   ", '\n')
cat("  ###-------------------------------------- ", '\n')
cat("  library(tidyr); library(dplyr) ", '\n')
cat("   ", '\n')
cat("  # wide format으로 변환 ", '\n')
cat("  data_wide <- data %>% ", '\n')
cat("    pivot_wider( ", '\n')
cat("      names_from = v2, ", '\n')
cat("      values_from = v4 ", '\n')
cat("    ) %>% ", '\n')
cat("    arrange(desc(v3))  # 연도 정렬 (옵션) ", '\n')
cat("   ", '\n')

}}
