# defining ts

e_ts<-function(explaining=0){
if(explaining==0) {
cat("    ", '\n')
cat("# create Time Series Objects ------------- ", '\n')
cat("  gold <- ts(log(dat$gold),start=c(1993,1),frequency=12)  ", '\n')
cat("    ", '\n')
cat(" library(ggfortify); library(ggplot2); library(aj412ts)    ", '\n')
cat(" ggsubseriesplot(gold) ", '\n')
cat(" ggseasonplot(gdp_sa, year.labels=T, year.labels.left=T)  ", '\n')
cat(" ggseasonplot 대체 명령문 -- aj412ts의 gs22  ", '\n')
cat(" gs22(gdp_sa) ", '\n')
cat("    ", '\n')
cat("# xts의 apply.quarterly()으로 월자료 -> 분기자료 ------------- ", '\n')
cat(" \033[1;32m 자료1<-xts(전산업생산지수$ind_m, order.by=전산업생산지수$date) #월별자료  \033[0m ", '\n')
cat(" \033[1;32m 자료2<-apply.quarterly(자료1, FUN=colMeans) #월자료 -> 3개월 평균 -> 분기자료  \033[0m ", '\n')
cat(" \033[1;32m    ", '\n')
cat(" \033[1;32m xtsdata <- xts(df$자료2, order.by=df$DATE) \033[0m", '\n')
cat(" \033[1;32m plot(xtsdata, main = '월별자료', col = 'blue') \033[0m", '\n')
cat("    ", '\n')
cat("# xts를 ts로 전환 ------------- ", '\n')
cat("  library(dsa)  ", '\n')
cat("  tmp <- xts2ts(xtsdata)  ", '\n')
cat("    ", '\n')
cat("# 경제성장률(분기별 gdp) ------------- ", '\n')
cat(" \033[1;32m 전년동기대비_GDP성장률 <- (gdp / dplyr::lag(gdp, 4) -1 )*100    \033[0m ", '\n')
cat("    ", '\n')
cat(" \033[1;34m# TS자료: 월 -> 분기: r<-stats::aggregate(ir, nfrequency=4)/3  #3개월 자료를 평균함 ", '\n')
cat(" \033[1;34m# TS자료: 연 -> 분기: library(tempdisagg) ", '\n')
cat(" \033[1;34m#                     td1<-td(cs~1, to='quarterly', converstion='last', method='denton-cholette') ", '\n')
cat("    ", '\n')
}}
