e_vars<-function(explaining=0){
if(explaining==0) {
cat("    ", '\n')
cat(" \033[1;34m# TS자료: 월 -> 분기: r<-aggregate(ir, nfrequency=4)/3  ", '\n')
cat(" \033[1;34m# TS자료: 연 -> 분기: library(tempdisagg) ", '\n')
cat(" \033[1;34m#                     td1<-td(cs~1, to='quarterly', converstion='last', method='denton-cholette') ", '\n')
cat("    ", '\n')
cat(" \033[1;34m# VECM vs. VAR ---------------- \033[0m", '\n')
cat(" \033[1;34m# VAR에 사용되는 데이터는 ts지정 필요없음 \033[0m", '\n')
cat(" \033[1;34m# VAR 변수 순서: 외생성이 크면 왼쪽, 내생성(다른 변수의 영향을 받음)이 크면 오른쪽  \033[0m", '\n')
cat(" \033[1;34m# 변수 순서는 VAR결과에 영향 없음. Cholesky분해, IRF 등에 영향 미침 \033[0m", '\n')
cat(" \033[1;34m# ... 왼쪽에 배치된 변수는 오른쪽 변수에 영향을 미칠 수 있지만,  \033[0m", '\n')
cat(" \033[1;34m# ... 오른쪽 변수는 왼쪽 변수에 영향을 미치지 않는다고 가정함  \033[0m", '\n')
cat("       ", '\n')
cat("# Canada자료는 1980년1분기-2000년4분기 동안의 분기별 고용(e), 노동생산성(prod),   ", '\n')
cat("    실질임금(rw), 실업(U)의 순서로 자료가 수록     ", '\n')
cat("    1. 고용(e)은 고용자수(단위:천명, E)에 자연로그를 취하고 100을 곱한 값     ", '\n')
cat("    2. prod는 노동자1인당 실질GDP에 대해 자연로그를 취하고 100을 곱한 값     ", '\n')
cat("    3. 실질임금(rw)은 실질임금에 자연로그를 취하고 100을 곱한 값   ", '\n')
cat("    4. U는 실업률(%)를 나타냄   ", '\n')
cat(" \033[1;35m   5. 변수 순서: prod->e->U->rw  \033[0m", '\n')
cat("       ", '\n')
cat(" \033[1;34m# autoplot으로 시계열자료 탐색 ----------  \033[0m", '\n')
cat("    library(ggfortify) ; library(ggplot2)  # ggfortify와 ggplot2를 함께 로딩 ", '\n')
cat("    df<-Canada; df<-data.frame(df) ", '\n')
cat("    df$e<-ts(df$e, start=c(1980, 1)) # data.frame의 임의 변수를 ts로 지정 ", '\n')
cat("    autoplot(cbind(df$e, df$prod, df$rw)) + theme_minimal() ", '\n')
cat("     ", '\n')
cat(" \033[1;34m# 단위근 검정  ---------------  \033[0m", '\n')
cat(" \033[1;33m  uroot(데이터셋, 변수명) <- aTSA::stationary.test(df$x, nlag=8) ", '\n')
cat("   단위근 검정에서 각 변수가 모두 Stationary이면 VAR를 사용  ", '\n')
cat("   Non-stationary변수를 차분하면 Stationary로 변화됨    ", '\n')
cat("       ", '\n')
cat(" \033[1;34m# 인과관계 검정 --------------- \033[0m", '\n')
cat(" \033[1;33m   VAR분석결과<-\033[1;32mVAR\033[0m(Canada, type ='const', p=2)  \033[0m", '\n')
cat(" \033[1;33m   \033[1;32mcausality\033[0m(VAR분석결과, cause = '변수명') \033[0m", '\n')
cat("     - 인과관계 검정에서 'Instant' 결과는 동시 상관성 검정  ", '\n')
cat("     - 동시 상관성은 시간적 순서없이 ", '\n')
cat("       두 변수간 관계가 동시적으로 존재하는지 확인  ", '\n')
cat("       ", '\n')
cat(" \033[1;34m# 공적분 검정 --------------- \033[0m", '\n')
cat("    # 공적분 >=1이면 VECM사용, 그렇지 않으면 VAR 사용 ", '\n')
cat("    # ca.jo 함수는 공적분 검정을 수행하는 함수로서,  ", '\n')
cat("    # 불안정 시계열 (non-stationary time series) 데이터를 입력받아야 함 ", '\n')
cat("    ", '\n')
cat(" \033[1;34m# Johansen Cointegration Test --------------- \033[0m", '\n')
cat(" \033[1;33m  \033[1;32mca.jo\033[0m(Canada, type='trace', ecdet='trend', K=3, spec='transitory') \033[0m", '\n')
cat("    ecdets는 'error correction term'의 종류를 지정하는 인자. 주어진 옵션... ", '\n')
cat("    ecdet = 'trend'는 상수 항과 추세 항이 모두 포함된 공적분 관계를 고려하여 검정을 수행 ", '\n')
cat("      'none': 상수 항이 없는 모델 ", '\n')
cat("      'const': 상수 항만 포함하는 모델 ", '\n')
cat("      'trend': 상수 항과 추세 항을 포함하는 모델 ", '\n')
cat("   ", '\n')
cat("    spec은 공적분 모델에서의 모델설정specification을 지정. spec에 사용할 수 있는 옵션... ", '\n')
cat("      'longrun': 공적분 관계가 장기적 균형 관계를 나타낸다고 가정하는 모델 ", '\n')
cat("                 변수들이 장기적으로 일정한 비율로 함께 움직인다는 가정 ", '\n')
cat("      'transitory': 변수들 간에 일시적인 관계를 고려하는 모델 ", '\n')
cat("                    변수들이 단기적으로 관계를 가질 수 있지만, 시간이 지나면서 그 관계가 지속되지 않는다고 보는 설정 ", '\n')
cat("      'both': 장기적이고 일시적인 관계를 모두 포함한 모델 ", '\n')
cat("              변수들이 장기적으로 균형을 이루는 관계와 단기적으로 일시적인 관계를 모두 고려하는 설정 ", '\n')
cat("   ", '\n')
cat("    K는 lag의 갯수를 지정 ", '\n')
cat("   ", '\n')
cat(" \033[1;34m# ca.jo 결과 해석 --------------- \033[0m", '\n')
cat("        결과해석: r=0부터 시작해 검정통계량이 경계값을 넘지 못하는 r값에서 STOP. STOP한 r이 공적분값  ", '\n')
cat("        r <= 1: 귀무가설은 '공적분 관계 최대 1개 이하'  ", '\n')
cat("        r = 0: 통계량 86.12 > 5% 임계값 62.99 → 귀무가설(r=0)을 기각 (공적분 관계가 있음)  ", '\n')
cat("        r ≤ 1: 통계량 37.33 < 5% 임계값 42.44 → 귀무가설(r≤1)을 기각하지 않음  ", '\n')
cat("               따라서, 공적분 관계는 1개 존재한다고 결론  ", '\n')
cat("       ", '\n')
cat(" \033[1;34m# 1차 차분하기 ---------------- \033[0m", '\n')
cat("   Canada<-mkdiff(Canada, e, prod, rw, U) ", '\n')
cat("   Canada2<-comp22(Canada)  ", '\n')
cat("   Canada3<-sel22(Canada2, d_prod, d_e, d_U, d_rw)  ", '\n')
cat("       ", '\n')
cat(" \033[1;34m# Lag길이 결정 ---------------  \033[0m", '\n')
cat(" \033[1;33m  VARselect( Canada2, type='const', lag.max=5)  # SC기준으로 lag는 1  \033[0m", '\n')
cat("             # type = const, trend, both, none  ", '\n')
cat("       ", '\n')
cat(" \033[1;34m# VAR분석 --------------- \033[0m", '\n')
cat(" \033[1;33m  Re1 <- VAR(Canada3, type='const', lag=4)   # p=2대신 lag=4를 사용하면 자동으로 Lag결정 \033[0m", '\n')
cat("   identt( residuals(Re1)[,1])  ", '\n')
cat("   qstat( residuals(Re1)[,1])  ", '\n')
cat("   serial.test(Re1, lags.pt=16, type='PT.asymptotic') ", '\n')
cat("   normality.test(Re1) ", '\n')
cat("   roots(Re1) # stable because all roots <1  ", '\n')
cat("   plot(stability(Re1), nc=2) ", '\n')
cat("    ", '\n')
cat(" \033[1;34m# exogen의 사용 --------------- \033[0m", '\n')
cat("   # VAR의 exogen 인수는 외생변수 지정에 사용 ", '\n')
cat("   # 외생변수는 모델의 내생 변수와는 독립적으로 주어지는 변수로서 ", '\n')
cat("   # 모델의 예측에 영향을 미치지만, 모델 내에서 설명되지 않는 변수 ", '\n')
cat("   # 예를 들어, 경제 데이터를 분석할 때 금리나 정책 변화와 같은 ", '\n')
cat("   # 외부 요인을 외생 변수로 포함할 수 있음 ", '\n')
cat("    ", '\n')
cat(" \033[1;32m  exogen_var\033[0m<-data.frame(Canada3[,c(3)]) ", '\n')
cat("    ", '\n')
cat("   Re2 <- VAR(Canada3[,c(1,2)], exogen=\033[1;32mexogen_var\033[0m, p=2) # p=2대신 lag=4를 사용하면 자동으로 Lag결정  ", '\n')
cat("   summary(Re2) ", '\n')
cat("   roots(Re2)  # ... it is stable because all roots <1  ", '\n')
cat("    ", '\n')
cat(" \033[1;34m# 충격반응함수(Impulse Response Function) 01 -------- \033[0m", '\n')
cat("  irf_result <- \033[1;32mirf\033[0m(var_model, impulse = NULL, response = NULL,  ", '\n')
cat("                               n.ahead = 10, ortho = FALSE) ", '\n')
cat("    한 단위 충격은 오차항 사이의 공분산으로 직접효과와 간접효과가 ", '\n')
cat("    모두 포함되어 있음. 간접효과를 배제하기 위해 Cholesky decomposition사용 ", '\n')
cat("    간접효과를 배제한 충격반응함수를 직교충격바응함수(orthogonalized IRF) ", '\n')
cat("    혹은 표준편차(one standard deviation)충격반응함수라 함. ", '\n')
cat("    일반적으로 사용되는 IRF는 간접효과를 배제한 직교IRF가 주로 사용됨. ", '\n')
cat("       ", '\n')
cat(" \033[1;34m# 충격반응함수(Impulse Response Function) 02 -------- \033[0m", '\n')
cat("  irf_result <- \033[1;32mirf\033[0m(var_model, impulse = NULL, response = NULL,  ", '\n')
cat("                               n.ahead = 10, ortho = TRUE) ", '\n')
cat("    impulse: 충격을 주고자 하는 변수(디폴트는 NULL로, 모든 변수를 포함). ", '\n')
cat("    response: 반응을 보고 싶은 변수(디폴트는 NULL로, 모든 변수를 포함). ", '\n')
cat("    n.ahead: 충격에 대한 반응을 예측할 기간(예: 10). ", '\n')
cat("    ortho = TRUE: Cholesky 분해를 사용하여 orthogonalized IRF 계산. ", '\n')
cat("  ", '\n')
cat("  ", '\n')
cat(" \033[1;34m# 충격반응함수(Impulse Response Function) 03 -------- \033[0m", '\n')
cat("    IRF.m11<-\033[1;32mirf\033[0m(Re1, impulse='d_ip', response='d_m1', ortho=T, n.ahead=30, boot=TRUE )   ", '\n')
cat("    plot(IRF.m11, ylab='m1반응', main='ip Shock')     ", '\n')
cat(" 	", '\n')
cat("    IRF.tb2<-\033[1;32mirf\033[0m(Re1, impulse='d_m1', response='d_tb', ortho=T, n.ahead=30, boot=TRUE )   ", '\n')
cat("    plot(IRF.tb2, ylab='tb반응', main='m1 Shock')     ", '\n')
cat("  ....", '\n')
cat(" 	", '\n')
cat("# ---------------	", '\n')
cat(" \033[1;34m# 예측오차분산분해: 한 변수의 충격 변동이 다른 변수 변동에  \033[0m", '\n')
cat(" \033[1;34m# 몇 %퍼센트 영향을 미치는지 상대적 중요도를 보여준다 \033[0m", '\n')
cat(" \033[1;33m    RE.fevd<-fevd(Re1, n.ahead=10, ci=0.95)  \033[0m", '\n')
cat(" \033[1;33m    p_fevd(RE.fevd, col=c('steelblue', 'salmon3', 'yellowgreen', 'blueviolet')) \033[0m", '\n')
cat("  ", '\n')
cat(" \033[1;34m# 예측치의 작성 ------------------   \033[0m", '\n')
cat(" \033[1;33m    predictions <- predict(Re1, n.ahead=10, ci=0.95 ) \033[0m", '\n')
cat("  ", '\n')
cat(" \033[1;34m# SVAR 모형추정예제1: A모형(장기제약조건 부과) ------------- \033[0m", '\n')
cat("     # 변수의 순서가 주요한데, prod->e->U->rw 순서임 ", '\n')
cat("     # 단기제약조건을 통해 n(n-1)/2=4*3=6개의 0의 단기제약조건 부과 ", '\n')
cat("     # 생산성은 즉각적으로 생산성충격에 의해서만 영향을 받음 => ((1,2), (1,3), (1,4))=0  ", '\n')
cat("     # 고용은 즉각적으로 생산성충격과 고용충격에 의해서만 영향을 받음 => ((2,3),(2,4))=0 ", '\n')
cat("     # 실업충격은 즉각적으로 생산성충격, 고용충격 및 실업충격에 의해서만 영향을 받음 => (3,4) => 0 ", '\n')
cat("  ", '\n')
cat("   # 수원시정연구원: 지방재정지출이 지역경제 및 경제성장에 미치는 영향 ", '\n')
cat(" \033[1;33m    amat  \033[0m", '\n')
cat("         [,1] [,2] [,3] [,4] ", '\n')
cat("      [1,]   NA    0    0    0 ", '\n')
cat("      [2,]   NA   NA    0    0 ", '\n')
cat("      [3,]   NA   NA   NA    0 ", '\n')
cat("      [4,]   NA   NA   NA   NA ", '\n')
cat("  ", '\n')
cat(" 	", '\n')
cat(" \033[1;34m# SVAR 모형추정예제2: A모형(단기제약조건 부과) ------------- \033[0m", '\n')
cat("  amat <- matrix(NA,4,4) ", '\n')
cat("  amat[lower.tri(amat)] <- 0 ", '\n')
cat("  diag(amat) <- 1 ", '\n')
cat("  svarresult <- \033[1;33mSVAR\033[0m(Re1, estmethod='scoring', Amat=amat) ", '\n')
cat("                        - estmethod는 구조적 VAR 분석에서 충격을 식별하기 위한 추정 방법을 지정 ", '\n')
cat("                        - 단기제약모형에서는 direct가 가장 많이 사용 ", '\n')
cat("                        - 장기제약모형에서는 일반적으로 scoring(=MLE) 사용 ", '\n')
cat("  summary(svarresult) ", '\n')
cat("  irfresult <- \033[1;33mirf\033[0m(svarresult, impuse=c('d_U'), response=c('d_prod', 'd_e', 'd_U', 'd_rw'),  ", '\n')
cat("  				  n.ahead=13, cumulative=T, boot=T, runs=100, ci=0.68) ", '\n')
cat("  plot(irfresult) ", '\n')
cat("  fevdresult <- \033[1;33mfevd\033[0m(svarresult, n.ahead=13) ", '\n')
cat("  par('mar') ", '\n')
cat("  par(mar=c(1,1,1,1)) ", '\n')
cat("  plot(fevdresult) ", '\n')
cat("  \033[1;33mp_fevd\033[0m(fevdresult, col=c('steelblue', 'salmon3', 'yellowgreen', 'blueviolet')) ", '\n')
cat("  fevdresult ", '\n')
cat(" ", '\n')
cat(" \033[1;33m#-------------------------------------- \033[0m", '\n')
cat(" \033[1;33m# VARselect lag 갯수의 결정. lag갯수가 K일 경우:\033[0m", '\n')
cat(" \033[1;33m#-------------------------------------- \033[0m", '\n')
cat(" \033[1;32m#  VAR :   lag = K \033[0m", '\n')
cat(" \033[1;32m#  VECM :  lag 갯수 = K-1 \033[0m", '\n')
cat(" \033[1;32m#  ca.jo : 최소lag = 2 \033[0m", '\n')
cat(" \033[1;32m#          lag = K-1 단, K>=3  \033[0m", '\n')
cat(" ", '\n')
cat(" \033[1;33m#-------------------------------------- \033[0m", '\n')
cat(" \033[1;33m# 분석에 필요한 Dataset:\033[0m", '\n')
cat(" \033[1;33m#-------------------------------------- \033[0m", '\n')
cat(" \033[1;32m#  VARselect : stationary자료 \033[0m", '\n')
cat(" \033[1;32m#  ca.jo     : 원자료 (NO차분) \033[0m", '\n')
cat(" \033[1;32m#  causality : VAR결과 \033[0m", '\n')
cat(" \033[1;32m#  \033[0m", '\n')

}}

