e_vars<-function(explaining=0){
if(explaining==0) {
cat("# VECM vs. VAR -------------------------------------- ", '\n')
cat("# Dicky-Fuller검정에서 각 변수가 모두 Stationary이면 VAR를 사용  ", '\n')
cat("# non-stationary변수를 difference하면 stationary로 변화됨    ", '\n')
cat("# Granger 인과분석에서 모든 변수가 내생변수면 VAR를 사용  ", '\n')
cat("# 변수를 위치시키는 순서는 내생성이 클수록 왼쪽, 외생성이 크면 오른쪽  ", '\n')
cat("# Bdata의 cointegration 검정 후, cointegration >=1이면, use VECM. Otherwise use VAR  ", '\n')
cat("#   ", '\n')
cat("# Johansen Cointegration Test ---------------  ", '\n')
cat("  coint.test2<-ca.jo(Bdata, type='eigen', ecdet='const', K=2) ", '\n')
cat("  summary(coint.test2) # 결과: cointegration=1     ", '\n')
cat("       ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("    ", '\n')
cat("  library(aTSA); library(vars); library(aj412ts) ", '\n')
cat("  df<-ekis_ch12  ", '\n')
cat("    ", '\n')
cat("# Lag길이 결정 ---------------   ", '\n')
cat("# type = const, trend, both, none  ", '\n')
cat("  VARselect(df[,2], lag.max=8, type='const')  # SC기준으로 lag는 2  ", '\n')
cat("  VARselect(df[,3], lag.max=8, type='const')  # SC기준으로 lag는 2  ", '\n')
cat("  .....  ", '\n')
cat("       ", '\n')
cat("# ADF Test for One variable ---------------   ", '\n')
cat("  adf.test( df[,2] )  ", '\n')
cat("  adf.test( df[,3] )  ", '\n')
cat("  adf.test( df[,4] )  ", '\n')
cat("       ", '\n')
cat("# 1차 차분하기 ----------------      ", '\n')
cat("  df<-mkdx(df, 2) ", '\n')
cat("  df<-mkdx(df, 3) ", '\n')
cat("  df<-mkdx(df, 4) ", '\n')
cat("       ", '\n')
cat("  # VAR변수 순서정하기. 내생성이 큰 변수 <- 외생성이 큰 변수 ", '\n')
cat("# 그랜저 인과관계 분석I ---------------  ", '\n')
cat("  grangertest(df[-c(1),c(5,6)], order=2)     ", '\n')
cat("  grangertest(df[-c(1),c(6,5)], order=2)     ", '\n')
cat("  grangertest(df[-c(1),c(5,7)], order=2)     ", '\n')
cat("  grangertest(df[-c(1),c(7,5)], order=2)     ", '\n')
cat("  grangertest(df[-c(1),c(6,7)], order=2)     ", '\n')
cat("  grangertest(df[-c(1),c(7,6)], order=2)     ", '\n')
cat("  ...     ", '\n')
cat("     ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("# VAR분석 ---------------  ", '\n')
cat("       ", '\n')
cat("  Re <- VAR(df[-c(1),c(5:7)], type='const', p=2) # p=2대신 lag=4를 사용하면 자동으로 Lag결정", '\n')
cat("       ", '\n')
cat("# 그랜저 인과관계 분석II ---------------  ", '\n')
cat("  causality(Re, cause='d_ip') ", '\n')
cat("  causality(Re, cause='d_m1') ", '\n')
cat("  causality(Re, cause='d_tb') ", '\n')
cat("       ", '\n')
cat("# 충격반응함수(Impulse Response Function)------------- ", '\n')
cat("  IRF.ip1<-irf(Re, impulse='d_m1', response='d_ip', n.ahead=30, boot=TRUE )   ", '\n')
cat("  plot(IRF.ip1, ylab='ip반응', main='m1 Shock')   ", '\n')
cat("  IRF.ip2<-irf(Re, impulse='d_tb', response='d_ip', n.ahead=30, boot=TRUE )   ", '\n')
cat("  plot(IRF.ip1, ylab='ip반응', main='tb Shock')   ", '\n')
cat("  IRF.m11<-irf(Re, impulse='d_ip', response='d_m1', n.ahead=30, boot=TRUE )   ", '\n')
cat("  plot(IRF.m11, ylab='m1반응', main='ip Shock')     ", '\n')
cat("  IRF.m12<-irf(Re, impulse='d_tb', response='d_m1', n.ahead=30, boot=TRUE )   ", '\n')
cat("  plot(IRF.m12, ylab='m1반응', main='tb Shock')     ", '\n')
cat("  IRF.tb1<-irf(Re, impulse='d_ip', response='d_tb', n.ahead=30, boot=TRUE )   ", '\n')
cat("  plot(IRF.tb1, ylab='tb반응', main='ip Shock')     ", '\n')
cat("  IRF.tb2<-irf(Re, impulse='d_m1', response='d_tb', n.ahead=30, boot=TRUE )   ", '\n')
cat("  plot(IRF.tb2, ylab='tb반응', main='m1 Shock')     ", '\n')
cat(" 				 ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" 				 ", '\n')
cat("# 예측오차분산분해: 한 변수의 충격 변동이 다른 변수 변동에 몇 %퍼센트 영향을 미치는지 상대적 중요도를 보여준다. ", '\n')
cat("  Re.fevd<-fevd(Re, n.ahead=10, ci=0.95)   ", '\n')
cat("  plot.varfevd(Re.fevd, col=c('steelblue', 'salmon3', 'yellowgreen'))    ", '\n')
cat("  ", '\n')
cat("# 예측치의 작성 ------------------       ", '\n')
cat("  predictions <- predict(Re, n.ahead=10, ci=0.95 )   ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("# SVAR-A model-------------   ", '\n')
cat("  ", '\n')
cat("  amat<-matrix(NA,3,3) ", '\n')
cat("  amat[upper.tri(amat)]<-0 ", '\n')
cat("  svarresult<-SVAR(Re, estmethod='scoring', Amat=amat) ", '\n')
cat("  summary(svarresult) ", '\n')
cat("  irfresult<-irf(svarresult, impuse=c('d_ip'), response=c('d_ip', 'd_m1', 'd_tb'),  ", '\n')
cat("  				  n.ahead=13, cumulative=T, boot=T, runs=100, ci=0.68) ", '\n')
cat("  plot(irfresult) ", '\n')
cat("  fevdresult<-fevd(svarresult, n.ahead=13) ", '\n')
cat("  plot.varfevd(fevdresult, col=c('steelblue', 'salmon3', 'yellowgreen')) ", '\n')
cat("  fevdresult ", '\n')
cat(" ", '\n')


}}

