e_vars<-function(explaining=0){
if(explaining==0) {
cat('\014')
cat("# VECM vs. VAR -------------------------------------- ", '\n')
cat("# Canada자료는 1980년1분기-2000년4분기 동안의 분기별 고용(e), 노동생산성(prod),   ", '\n')
cat("    실질임금(rw), 실업(U)의 순서로 자료가 수록     ", '\n')
cat("    1. 고용(e)은 고용자수(단위:천명, E)에 자연로그를 취하고 100을 곱한 값     ", '\n')
cat("    2. prod는 노동자1인당 실질GDP에 대해 자연로그를 취하고 100을 곱한 값     ", '\n')
cat("    3. 실질임금(rw)은 실질임금에 자연로그를 취하고 100을 곱한 값   ", '\n')
cat("    4. U는 실업률(%)를 나타냄   ", '\n')
cat("       ", '\n')
cat("# VAR에 사용되는 데이터는 ts지정 필요없음   ", '\n')
cat("       ", '\n')
cat("# Dicky-Fuller검정에서 각 변수가 모두 Stationary이면 VAR를 사용  ", '\n')
cat("       ", '\n')
cat("# non-stationary변수를 difference하면 stationary로 변화됨    ", '\n')
cat("       ", '\n')
cat("# Granger 인과분석에서 모든 변수가 내생변수면 VAR를 사용  ", '\n')
cat("       ", '\n')
cat("# 변수를 위치시키는 순서는 내생성이 클수록 왼쪽, 외생성이 크면 오른쪽  ", '\n')
cat("# 원자료의 cointegration 검정 후, cointegration >=1이면, use VECM. Otherwise use VAR  ", '\n')
cat("#   ", '\n')
cat("# Cointegration 검정을 통해 공적분이 없으면 VAR를 사용하고, 공적분이 있으면 VECM을 사용함 ", '\n')
cat("# Johansen Cointegration Test ---------------  ", '\n')
cat("  summary(ca.jo(Canada, type='trace', ecdet='trend', K=3, spec='transitory')) ", '\n')
cat("  결과해석: r=0부터 시작해 검정통계량이 경계값을 넘지 못하는 r값에서 STOP. STOP한 r이 공적분값  ", '\n')
cat("       ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat('\014')
cat("# VAR분석 ---------------  ", '\n')
cat("    ", '\n')
cat("  df<-Canada  ", '\n')
cat("  df<-as.data.frame(df)  ", '\n')
cat("  df<-mkdate_series(df, 1980, 1, 4)  ", '\n')
cat("  df<-mkdate_form(df, 'DATE')  ", '\n')
cat("  df <- df %>% relocate(DATE, .before='e')  ", '\n')
cat("  colnames(df)<-c('DATE', 'e', 'prod', 'rw', 'U')  ", '\n')
cat("  # ADF Test for One variable ---------------  ", '\n')
cat("  # autoplot(df[,4]) 은 ts지정이 필요해 번거로움  ", '\n')
cat("  plot( df[, c(1:5)]  )  ", '\n')
cat("    ", '\n')
cat("# 1차 차분하기 ----------------  ", '\n')
cat("  df<-mkd(df, 'e'); df<-mkd(df, 'prod'); df<-mkd(df, 'rw'); df<-mkd(df, 'U')  ", '\n')
cat("  df<-comp22(df)   #complete.cases의 축약 명령문  ", '\n')
cat("  head(df)   ", '\n')
cat("       ", '\n')
cat("# Lag길이 결정 ---------------   ", '\n')
cat("# Canada3<-df[, c('d_prod', 'd_e', 'd_U', 'd_rw')]   ", '\n')
cat("# type = const, trend, both, none  ", '\n')
cat("  VARselect(Canada3, lag.max=8, type='const')  # SC기준으로 lag는 2  ", '\n')
cat("       ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat('\014')
cat("# VAR분석 ---------------  ", '\n')
cat("       ", '\n')
cat("  Re1 <- VAR(Canada3, type='const', p=2) # p=2대신 lag=4를 사용하면 자동으로 Lag결정 ", '\n')
cat(" 	", '\n')
cat("  plot(stability(Re1), nc=2) ", '\n')
cat(" 	", '\n')
cat("  serial.test(Re1, lags.pt=16, type='PT.asymptotic') ", '\n')
cat("  # serial.test 결과 오차항간에 계열상관이 존재하지 않음 ", '\n')
cat("       ", '\n')
cat("  normality.test(Re1) ", '\n')
cat(" 	", '\n')
cat("  # 이상의 3가지 테스트 결과 시차 2개를 포함하고 차분된 변수를 이용해 ", '\n')
cat("  # 측정한 VAR모형의 오차항은 바람직한 형태를 보이고 있음 ", '\n')
cat(" 	", '\n')
cat("  roots(Re1) # stable because all roots <1  ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat('\014')
cat(" # exogen의 사용 ------------------------- ", '\n')
cat("    ", '\n')
cat(" # VAR의 exogen 인수는 외생변수 지정에 사용 ", '\n')
cat(" # 외생변수는 모델의 내생 변수와는 독립적으로 주어지는 변수로서 ", '\n')
cat(" # 모델의 예측에 영향을 미치지만, 모델 내에서 설명되지 않는 변수 ", '\n')
cat(" # 예를 들어, 경제 데이터를 분석할 때 금리나 정책 변화와 같은 ", '\n')
cat(" # 외부 요인을 외생 변수로 포함할 수 있음. 이를 통해 ", '\n')
cat(" # 모델의 예측 정확도를 높일 수 있음  ", '\n')
cat("    ", '\n')
cat(" exogen_var<-data.frame(Canada3[,c(4)]) ", '\n')
cat(" Re2 <- VAR(Canada3[,c(1,2,3)], exogen=exogen_var, p=2) # p=2대신 lag=4를 사용하면 자동으로 Lag결정  ", '\n')
cat(" summary(Re2) ", '\n')
cat(" roots(Re2) # It is stable because all roots <1  ", '\n')
cat("    ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("\014")
cat("# 그랜저 인과관계 분석 ---------------  ", '\n')
cat("    ", '\n')
cat("  causality(Re1, cause='d_prod') # d_prod does not cause other variables", '\n')
cat("  causality(Re1, cause='d_e')  ", '\n')
cat("  causality(Re1, cause='d_U')  ", '\n')
cat("  causality(Re1, cause='d_rw')  ", '\n')
cat("       ", '\n')
cat("# 충격반응함수(Impulse Response Function) 수정하기 귀챦아서 과거 자료 그대로 보여줌. 수정 필요-------- ", '\n')
cat("  IRF.prod<-irf(Re1, impulse='d_m1', response='d_ip', ortho=T, n.ahead=30, boot=TRUE )   ", '\n')
cat("  plot(IRF.ip1, ylab='ip반응', main='m1 Shock')   ", '\n')
cat("  IRF.ip2<-irf(Re1, impulse='d_tb', response='d_ip', ortho=T, n.ahead=30, boot=TRUE )   ", '\n')
cat("  plot(IRF.ip1, ylab='ip반응', main='tb Shock')   ", '\n')
cat("  IRF.m11<-irf(Re1, impulse='d_ip', response='d_m1', ortho=T, n.ahead=30, boot=TRUE )   ", '\n')
cat("  plot(IRF.m11, ylab='m1반응', main='ip Shock')     ", '\n')
cat("  IRF.m12<-irf(Re1, impulse='d_tb', response='d_m1', ortho=T, n.ahead=30, boot=TRUE )   ", '\n')
cat("  plot(IRF.m12, ylab='m1반응', main='tb Shock')     ", '\n')
cat("  IRF.tb1<-irf(Re1, impulse='d_ip', response='d_tb', ortho=T, n.ahead=30, boot=TRUE )   ", '\n')
cat("  plot(IRF.tb1, ylab='tb반응', main='ip Shock')     ", '\n')
cat("  IRF.tb2<-irf(Re1, impulse='d_m1', response='d_tb', ortho=T, n.ahead=30, boot=TRUE )   ", '\n')
cat("  plot(IRF.tb2, ylab='tb반응', main='m1 Shock')     ", '\n')
cat(" 	", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("\014")
cat(" 	", '\n')
cat("# ---------------	", '\n')
cat("# 예측오차분산분해: 한 변수의 충격 변동이 다른 변수 변동에 몇 %퍼센트 영향을 미치는지 상대적 중요도를 보여준다. ", '\n')
cat("  Re.fevd<-fevd(Re1, n.ahead=10, ci=0.95)   ", '\n')
cat("  plot.varfevd(Re.fevd, col=c('steelblue', 'salmon3', 'yellowgreen', 'blueviolet'))    ", '\n')
cat("  ", '\n')
cat("# 예측치의 작성 ------------------       ", '\n')
cat("  predictions <- predict(Re1, n.ahead=10, ci=0.95 )   ", '\n')
cat("  ", '\n')
cat("# SVAR 모형추정예제1: A모형(단기제약조건 부과) ", '\n')
cat("# 변수의 순서가 주요한데, prod->e->U->rw 순서임 ", '\n')
cat("# 단기제약조건을 통해 n(n-1)/2=4*3=6개의 0의 단기제약조건 부과 ", '\n')
cat("# 생산성은 즉각적으로 생산성충격에 의해서만 영향을 받음 => ((1,2), (1,3), (1,4))=0  ", '\n')
cat("# 고용은 즉각적으로 생산성충격과 고용충격에 의해서만 영향을 받음 => ((2,3),(2,4))=0 ", '\n')
cat("# 실업충격은 즉각적으로 생산성충격, 고용충격 및 실업충격에 의해서만 영향을 받음 => (3,4) => 0 ", '\n')
cat("  ", '\n')
cat(" amat ", '\n')
cat("    [,1] [,2] [,3] [,4] ", '\n')
cat(" [1,]   NA    0    0    0 ", '\n')
cat(" [2,]   NA   NA    0    0 ", '\n')
cat(" [3,]   NA   NA   NA    0 ", '\n')
cat(" [4,]   NA   NA   NA   NA ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("\014")
cat(" 	", '\n')
cat("# SVAR-A model-------------   ", '\n')
cat("  ", '\n')
cat("  amat<-matrix(NA,4,4) ", '\n')
cat("  amat[upper.tri(amat)]<-0 ", '\n')
cat("  svarresult<-SVAR(Re1, estmethod='scoring', Amat=amat) ", '\n')
cat("  summary(svarresult) ", '\n')
cat("  irfresult<-irf(svarresult, impuse=c('d_U'), response=c('d_prod', 'd_e', 'd_U', 'd_rw'),  ", '\n')
cat("  				  n.ahead=13, cumulative=T, boot=T, runs=100, ci=0.68) ", '\n')
cat("  plot(irfresult) ", '\n')
cat("  fevdresult<-fevd(svarresult, n.ahead=13) ", '\n')
cat("  par('mar') ", '\n')
cat("  par(mar=c(1,1,1,1)) ", '\n')
cat("  plot(fevdresult) ", '\n')
cat("  plot.varfevd(fevdresult, col=c('steelblue', 'salmon3', 'yellowgreen', 'blueviolet')) ", '\n')
cat("  fevdresult ", '\n')
cat(" ", '\n')

}}

