# e_VECM()

e_VECM<-function(explaining=0){
if(explaining==0) {
cat("------------------------------------------------------------------------ ", '\n')
cat(" \033[1;32m# (1) lag길이 결정 \033[0m", '\n')
cat("VARselect(dat.VAR, lag.max=5, type='const') ", '\n')
cat("## type = const, trend, both, none  ", '\n')
cat("------------------------------------------------------------------------ ", '\n')
cat(" \033[1;32m# (2) 공적분 점검 \033[0m", '\n')
cat("ca.jo(x, type = c('trace', 'eigen'), ecdet = c('none', 'const', 'trend'), K=2)", '\n')
cat("## K=2(Lag갯수), spec=c('longrun', 'transitory') ", '\n')
cat("## K=2 : lag order of the series (levels) in the VAR ", '\n')
cat("## season = NULL, dumvar = NULL) ", '\n')
cat("## spec : longrun=요한센모형 : transitory=변형된 요한센모형, '\n') ", '\n')
cat("------------------------------------------------------------------------ ", '\n')
cat(" \033[1;32m# (3) VECM모형 실행 \033[0m", '\n')
cat("Result<-VECM(dat.VAR, lag=1, r=1, estim = 'ML', LRinclude = 'none')", '\n')
cat("## r=1 => I(1) , estim = c('2OLS', 'ML'), LRinclude => 2OLS only  ", '\n')
cat("------------------------------------------------------------------------ ", '\n')
cat("  ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" \033[1;32m# VECM분석 -------------- \033[0m", '\n')
cat("       ", '\n')
cat("  library(tsDyn)    ", '\n')
cat("  Bdata <- cbind(ip,m1,tb)  ", '\n')
cat("  Bdata <- as.data.frame(Bdata)  ", '\n')
cat("  VECM.model <- VECM(Bdata, 3, r = 1, estim =('2OLS'))  ", '\n')
cat("  # 3->lags, r=1->number of cointegration  ", '\n')
cat("  summary(VECM.model)  ", '\n')
cat("          ", '\n')
cat("# Diagnostic Tests - Need to Transform VECM to VAR      ", '\n')
cat("  VAR.model <- vec2var(coint.test1, r = 1)      ", '\n')
cat("      ", '\n')
cat("# Serial Correlation Test ----     ", '\n')
cat("  Serial.test <- serial.test(VAR.model, lags.pt = 16, type = 'PT.asymptotic')      ", '\n')
cat("  Serial.test      ", '\n')
cat("      ", '\n')
cat("# ARCH Effects Test ----     ", '\n')
cat("  Arch.test <- arch.test(VAR.model, lags.multi = 16, multivariate.only = TRUE)      ", '\n')
cat("  Arch.test      ", '\n')
cat("      ", '\n')
cat("# Normality of Residuals ----     ", '\n')
cat("  Norm.test <- normality.test(VAR.model, multivariate.only = TRUE)      ", '\n')
cat("  Norm.test   ", '\n')
cat("      ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("# Impulse Response Functions ----     ", '\n')
cat("# 일부 결과만 예를 들었음 ----  ", '\n')
cat("  IRF.ip <- irf(VAR.model, impulse = 'm1', response = 'ip', n.ahead = 20, boot = TRUE)      ", '\n')
cat("  plot(IRF.ip, ylab = 'ip반응', main = 'm1 Shock')      ", '\n')
cat("      ", '\n')
cat("  IRF.m1 <- irf(VAR.model, impulse = 'tb', response = 'm1', n.ahead = 20, boot = TRUE)      ", '\n')
cat("  plot(IRF.m1,  ylab = 'm1', main = 'tb Shock')      ", '\n')
cat("    ", '\n')
cat("  IRF.tb <- irf(VAR.model, impulse = 'tb', response = 'tb', n.ahead = 20, boot = TRUE)      ", '\n')
cat("  plot(IRF.tb,  ylab = 'tb', main = 'tb Shock')      ", '\n')
cat("      ", '\n')
cat("#Variance Decomposition      ", '\n')
cat("  FEVD1 <- fevd(VAR.model, n.ahead = 20)   ", '\n')
cat("  plot.varfevd(FEVD1, col=c('steelblue', 'salmon3', 'yellowgreen'))  ", '\n')
cat("      ", '\n')
cat("## 예측치 구하기(Predictions)--------", '\n')
cat("predictions <- predict(VAR결과, n.ahead=5, ci=0.95 )", '\n')
cat("predictions", '\n')
}}
